### ISSUE TITLE
开机花屏，卡8个苹果

### ISSUE THREAD

**Issue by lh123lh** [lgs3137/ASUS_Y5000U_X507UBR-macOS#1]
机型是一样的，我自己配置的clover可以正常启动，用了这个配置开机会卡8个苹果

**Comment by lgs3137** [comment]
不会吧？我一直用着10.14.6正常，没换过任何硬件

**Comment by lh123lh** [comment]
> 不会吧？我一直用着10.14.6正常，没换过任何硬件
